[build]
  command = "npm run build"
  functions = "functions/"
  publish = "build"
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[[redirects]]
  from = "/"
  to = "https://landing.amingos.io/"
  force = true
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200